import './style.css';

const API_ROOT = 'https://www.googleapis.com/youtube/v3';
const API_KEY = import.meta.env.VITE_YOUTUBE_API_KEY;
const categories = ['All', 'Music', 'Podcasts', 'Documentary', 'Live', 'Technology', 'Travel', 'Design'];
const categoryIds = { Music: '10', Gaming: '20', News: '25', Sports: '17' };
const fallbackVideos = [
  { id: 'dQw4w9WgXcQ', title: 'A little bit of internet history', channel: 'YouTube', description: 'Discover something worth watching today.', thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg', views: 'Featured video', published: 'Today', duration: '3:32' },
  { id: 'M7lc1UVf-VE', title: 'Build something people want to use', channel: 'YouTube Developers', description: 'Ideas, tools, and stories from the YouTube community.', thumbnail: 'https://i.ytimg.com/vi/M7lc1UVf-VE/hqdefault.jpg', views: 'Featured video', published: 'Today', duration: '4:20' },
  { id: 'ysz5S6PUM-U', title: 'Live from the edge of the atmosphere', channel: 'YouTube', description: 'A fresh window into the world around us.', thumbnail: 'https://i.ytimg.com/vi/ysz5S6PUM-U/hqdefault.jpg', views: 'Featured video', published: 'Today', duration: '8:14' },
  { id: 'aqz-KE-bpKQ', title: 'A walk through a city that never stops', channel: 'YouTube', description: 'Take a slower look at somewhere new.', thumbnail: 'https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg', views: 'Featured video', published: 'Today', duration: '5:12' },
];
const state = { query: '', category: 'All', videos: [], nextPageToken: '', loading: false, error: '' };
const icons = { menu: '<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>', search: '<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/></svg>', home: '<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z"/></svg>', play: '<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6V6Z"/></svg>', close: '<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>' };

function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function formatCount(value = 0) { return new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(Number(value)); }
function formatDuration(value = 'PT0S') { const match = value.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/); if (!match) return 'LIVE'; const hours = Number(match[1] || 0); const minutes = Number(match[2] || 0); const seconds = Number(match[3] || 0); return hours ? `${hours}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}` : `${minutes}:${String(seconds).padStart(2, '0')}`; }
function normalize(item, details = {}) { const snippet = item.snippet || {}; return { id: item.id?.videoId || item.id, title: snippet.title || '', description: snippet.description || '', channel: snippet.channelTitle || '', published: snippet.publishedAt ? new Date(snippet.publishedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '', thumbnail: snippet.thumbnails?.maxres?.url || snippet.thumbnails?.high?.url || snippet.thumbnails?.medium?.url || '', views: details.statistics?.viewCount ? `${formatCount(details.statistics.viewCount)} views` : 'YouTube video', duration: details.contentDetails?.duration ? formatDuration(details.contentDetails.duration) : '' }; }
async function youtube(path, params) { const url = new URL(`${API_ROOT}/${path}`); Object.entries({ ...params, key: API_KEY }).forEach(([key, value]) => value && url.searchParams.set(key, value)); const response = await fetch(url); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'YouTube API request failed.'); return payload; }

async function fetchVideos(append = false) {
  state.loading = true; state.error = ''; render();
  try {
    if (!API_KEY) throw new Error('offline');
    const params = { part: 'snippet', maxResults: '12', type: 'video', q: state.query || undefined, pageToken: append ? state.nextPageToken : undefined, order: state.query ? 'relevance' : 'date' };
    if (categoryIds[state.category]) params.videoCategoryId = categoryIds[state.category];
    const result = await youtube('search', params); const ids = result.items.map((item) => item.id.videoId).join(','); const details = ids ? await youtube('videos', { part: 'snippet,contentDetails,statistics', id: ids }) : { items: [] }; const detailMap = new Map(details.items.map((item) => [item.id, item]));
    state.videos = append ? [...state.videos, ...result.items.map((item) => normalize(item, detailMap.get(item.id.videoId))).filter((video) => video.id)] : result.items.map((item) => normalize(item, detailMap.get(item.id.videoId))).filter((video) => video.id); state.nextPageToken = result.nextPageToken || '';
  } catch { state.videos = append ? state.videos : fallbackVideos; state.nextPageToken = ''; }
  state.loading = false; render();
}

function shell() { document.querySelector('#app').innerHTML = `<header class="topbar"><button class="icon-button menu-toggle" aria-label="Toggle menu">${icons.menu}</button><a class="brand" href="#"><span class="brand-mark">P</span><span>pulse</span></a><form class="search-form" id="search-form"><input id="search-input" type="search" placeholder="Search YouTube" autocomplete="off"><button aria-label="Search">${icons.search}</button></form><button class="avatar" aria-label="Account">A</button></header><div class="layout"><aside class="sidebar" id="sidebar"><nav><button class="nav-item active" data-category="All">${icons.home}<span>Home</span></button><button class="nav-item" data-category="Music">${icons.play}<span>Music</span></button><button class="nav-item" data-category="Live">${icons.play}<span>Live</span></button></nav><div class="nav-divider"></div><p class="nav-label">Explore</p><div class="topic-list">${categories.slice(1).map((category) => `<button data-category="${category}">${category}</button>`).join('')}</div></aside><main class="content"><section class="welcome"><div><p class="eyebrow">YouTube discovery</p><h1>Find your next <em>favorite</em> thing.</h1><p class="welcome-copy">Real videos, live search, and the official YouTube player.</p></div><div class="signal"><span class="signal-dot"></span><span>Live API feed</span></div></section><div class="category-scroll">${categories.map((category) => `<button class="chip ${category === 'All' ? 'active' : ''}" data-category="${category}">${category}</button>`).join('')}</div><section id="feature"></section><section class="section-heading"><div><p class="eyebrow">From YouTube</p><h2 id="feed-title">Trending now</h2></div><button class="text-button" id="refresh">Refresh ${icons.play}</button></section><div class="video-grid" id="video-grid"></div><button class="load-more" id="load-more">Load more videos</button></main></div><div class="player-modal" id="player-modal" aria-hidden="true"><div class="modal-backdrop" data-close-player></div><div class="player-dialog"><button class="icon-button close-player" data-close-player aria-label="Close player">${icons.close}</button><div class="player-frame" id="player-frame"></div><div class="player-meta" id="player-meta"></div></div></div>`; }

function render() { const grid = document.querySelector('#video-grid'); if (!grid) return; grid.innerHTML = state.loading ? '<div class="loading-state">Loading from YouTube<span>...</span></div>' : state.videos.length ? state.videos.map((video) => `<article class="video-card"><button class="thumbnail-wrap" data-video-id="${escapeHtml(video.id)}" aria-label="Play ${escapeHtml(video.title)}"><img src="${escapeHtml(video.thumbnail)}" alt=""><span class="duration">${video.duration || 'WATCH'}</span><span class="play-hover">${icons.play}</span></button><div class="video-info"><div class="channel-avatar">${escapeHtml((video.channel || 'Y')[0])}</div><div class="video-copy"><h3>${escapeHtml(video.title)}</h3><p>${escapeHtml(video.channel)}</p><small>${escapeHtml(video.views)} · ${escapeHtml(video.published)}</small></div></div></article>`).join('') : '<div class="empty-state"><strong>No videos found.</strong><span>Try another search or category.</span></div>'; const feature = document.querySelector('#feature'); feature.innerHTML = state.videos[0] ? `<article class="feature-card" style="--feature-image:url('${escapeHtml(state.videos[0].thumbnail)}')"><div class="feature-overlay"></div><div class="feature-content"><span class="feature-tag">Spotlight · ${escapeHtml(state.category)}</span><h2>${escapeHtml(state.videos[0].title)}</h2><p>${escapeHtml(state.videos[0].description)}</p><button class="watch-button" data-video-id="${escapeHtml(state.videos[0].id)}">${icons.play} Watch now</button></div></article>` : ''; document.querySelector('#load-more').hidden = !state.nextPageToken || state.loading; }
function openPlayer(id) { const video = state.videos.find((item) => item.id === id); if (!video) return; document.querySelector('#player-frame').innerHTML = `<iframe src="https://www.youtube.com/embed/${encodeURIComponent(id)}?autoplay=1&rel=0" title="${escapeHtml(video.title)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`; document.querySelector('#player-meta').innerHTML = `<h2>${escapeHtml(video.title)}</h2><p>${escapeHtml(video.channel)} · ${escapeHtml(video.views)}</p>`; document.querySelector('#player-modal').classList.add('open'); }
function closePlayer() { document.querySelector('#player-modal').classList.remove('open'); document.querySelector('#player-frame').innerHTML = ''; }
function chooseCategory(category) { state.category = category; state.query = ''; document.querySelector('#search-input').value = ''; document.querySelectorAll('[data-category]').forEach((item) => item.classList.toggle('active', item.dataset.category === category)); document.querySelector('#feed-title').textContent = category === 'All' ? 'Trending now' : `${category} picks`; fetchVideos(); }

shell();
document.addEventListener('click', (event) => { const category = event.target.closest('[data-category]'); if (category) return chooseCategory(category.dataset.category); const video = event.target.closest('[data-video-id]'); if (video) return openPlayer(video.dataset.videoId); if (event.target.closest('[data-close-player]')) return closePlayer(); if (event.target.closest('.menu-toggle')) document.querySelector('#sidebar').classList.toggle('open'); if (event.target.closest('#refresh')) fetchVideos(); if (event.target.closest('#load-more')) fetchVideos(true); });
document.querySelector('#search-form').addEventListener('submit', (event) => { event.preventDefault(); state.query = document.querySelector('#search-input').value.trim(); state.category = 'All'; document.querySelector('#feed-title').textContent = state.query ? `Results for “${state.query}”` : 'Trending now'; fetchVideos(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closePlayer(); });
fetchVideos();